// symbol index generated by DDOX - do not edit
var symbols = [
{name: 'mofile', kind: "module", path: './mofile.html', attributes: []},
{name: 'mofile.MoFile', kind: "structdeclaration", path: './mofile/MoFile.html', attributes: []},
{name: 'mofile.MoFile.gettext', kind: "functiondeclaration", path: './mofile/MoFile.gettext.html', attributes: ["pure", "safe", "const"]},
{name: 'mofile.MoFile.header', kind: "functiondeclaration", path: './mofile/MoFile.header.html', attributes: ["pure", "safe", "const"]},
{name: 'mofile.MoFile.ngettext', kind: "functiondeclaration", path: './mofile/MoFile.ngettext.html', attributes: ["pure", "safe", "const"]},
{name: 'mofile.MoFile.this', kind: "functiondeclaration", path: './mofile/MoFile.this.html', attributes: ["ref", "trusted"]},
{name: 'mofile.MoFileException', kind: "classdeclaration", path: './mofile/MoFileException.html', attributes: []},
{name: 'mofile.PluralFormException', kind: "classdeclaration", path: './mofile/PluralFormException.html', attributes: []},
];
