name: build
on:
  pull_request:
  push:
  release:
    types: [published]

jobs:
  Build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        test_type: [unittest]
        dc:
          - ldc-latest
          - dmd-latest
        exclude:
          - os: ubuntu-latest
            dc: dmd-latest
        include:
          - os: ubuntu-latest
            dc: dmd-latest
            test_type: unittest-cov
            use_doveralls: true
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup D
        uses: dlang-community/setup-dlang@v1
        with:
          compiler: ${{ matrix.dc }}

      # Build

      - name: Build and run tests
        run: |
          dub test -b ${{ matrix.test_type }}
      - name: Install and run doveralls
        if: ${{ matrix.use_doveralls == true && github.event_name == 'push' }}
        run: |
          sudo apt-get install -y libcurl4-openssl-dev
          dub fetch doveralls
          dub run doveralls -- -t ${{ secrets.CoverallsToken }}
